# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iskcv7oUQoEwDhQ_EVoa5LiSJEK2Fbl
"""

!pip install openai

import openai
openai.api_key = "sk-...kMEM"

import openai

with open("/content/Aaryann Mavani.opus", "rb") as audio_file:
    transcript = openai.Audio.transcribe(
        file = audio_file,
        model = "whisper-1",
        response_format="text",
        language="en"
    )
print(transcript)

!openai migrate